<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ вакансий из HeadHunter
   

In [4]:
import pandas as pd
import psycopg2

In [5]:
# вставьте сюда параметры подключения из юнита 1. Работа с базой данных из Python 


In [264]:
connection = psycopg2.connect(
    dbname=DBNAME,
    user=USER,
    host=HOST,
    password=PASSWORD,
    port=PORT
)

# Юнит 3. Предварительный анализ данных

1. Напишите запрос, который посчитает количество вакансий в нашей базе (вакансии находятся в таблице vacancies). 

In [277]:
# текст запроса
query_3_1 = f'''select 
                    count(name) -- Считаем количество вакансий
                from vacancies -- Работаем с таблицей vacancies
'''
df = pd.read_sql_query(query_3_1, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\3044144012.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_1, connection) # Создаем DF


count
0  49197

In [ ]:
# результат запроса
    count
0	49197

2. Напишите запрос, который посчитает количество работодателей (таблица employers). 

In [278]:
# текст запроса
query_3_2 = f'''select  
                    count(name) -- Считаем количество работодателей
                from employers -- Работаем с таблицей employers
'''
df = pd.read_sql_query(query_3_2, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\3656697592.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_2, connection) # Создаем DF


count
0  23501

In [ ]:
# результат запроса
    count
0	23501

3. Посчитате с помощью запроса количество регионов (таблица areas).

In [279]:
# текст запроса
query_3_3 = f'''select  
                    count(name) -- Считаем количество регионов
                from areas -- Работаем с таблицей areas
'''
df = pd.read_sql_query(query_3_3, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\4056565013.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_3, connection) # Создаем DF


count
0   1362

In [ ]:
# результат запроса
    count
0	1362

4. Посчитате с помощью запроса количество сфер деятельности в базе (таблица industries).

In [280]:
# текст запроса
query_3_4 = f'''select 
                    count(name) -- Считаем количество сфер деятельности
                from industries -- Работаем с таблицей industries
'''
df = pd.read_sql_query(query_3_4, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\1335184135.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_3_4, connection) # Создаем DF


count
0    294

In [ ]:
# результат запроса
    count
0	294

***

## Выводы по предварительному анализу данных:
* ### Нам предстоит работать почти с 50000 вакансий (любой соискатель может найти себе работу по душе:));
* ### Работодателей представлено в наших данных 23501, что на первый взгляд наталкивает на мысль о том, что на каждого работодателя в среднем приходится по 2 вакансии;
* ### 294 сферы деятельности дают понять, что в наших данных собраны вакансии почти всех сфер, и данные не являются узконаправленными, например только об IT.

# Юнит 4. Детальный анализ вакансий

1. Напишите запрос, который позволит узнать, сколько (cnt) вакансий в каждом регионе (area).
Отсортируйте по количеству вакансий в порядке убывания.

In [281]:
# текст запроса
query_4_1 = f'''select 
                    count(v.name) cnt, -- Считаем количество вакансий, называем столбец cnt
                    a.name area -- Выводим названия регионов, называем столбец area
                from vacancies v -- Работаем с таблицей vacancies
                    join areas a on v.area_id = a.id -- По ключу присоединяем таблицу areas
                group by 2 -- Группируем по названию регионов
                order by 1 desc -- Сортируем по количеству вакансий в порядке убывания
'''
df = pd.read_sql_query(query_4_1, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\1912367237.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_1, connection) # Создаем DF


cnt             area
0    5333           Москва
1    2851  Санкт-Петербург
2    2112            Минск
3    2006      Новосибирск
4    1892           Алматы
..    ...              ...
764     1       Тарко-Сале
765     1    Новоаннинский
766     1            Бирск
767     1           Сасово
768     1             Анна

[769 rows x 2 columns]

In [ ]:
# результат запроса
    cnt	    area
0	5333	Москва
1	2851	Санкт-Петербург
2	2112	Минск
3	2006	Новосибирск
4	1892	Алматы
...	...	    ...
764	1	    Тарко-Сале
765	1	    Новоаннинский
766	1	    Бирск
767	1	    Сасово
768	1	    Анна


2. Напишите запрос, чтобы определить у какого количества вакансий заполнено хотя бы одно из двух полей с зарплатой.

In [288]:
# текст запроса
query_4_2 = f'''select 
                    count(name) -- Считаем количество вакансий
                from vacancies -- Работаем с таблицей vacancies
                where (salary_from is not null or salary_to is not null) -- Добавляем условие заполнения хотя бы одного из полей
'''
df = pd.read_sql_query(query_4_2, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\3675966047.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_2, connection) # Создаем DF


count
0  24073

In [ ]:
# результат запроса 
    count
0	24073

3. Найдите средние значения для нижней и верхней границы зарплатной вилки. Округлите значения до целого.

In [283]:
# текст запроса
query_4_3 = f'''select 
                    round(avg(salary_from))::int down,  -- Находим среднее значение нижней границы ЗП, называем столбец down
                    round(avg(salary_to))::int up -- Находим среднее значение верхней границы ЗП, называем столбец up
                from vacancies -- Работаем с таблицей vacancies
'''
df = pd.read_sql_query(query_4_3, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\3627485850.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_3, connection) # Создаем DF


down      up
0  71065  110537

In [ ]:
# результат запроса
    down	   up
	71065	   110537

4. Напишите запрос, который выведет количество вакансий для каждого сочетания типа рабочего графика (schedule) и типа трудоустройства (employment), используемого в вакансиях. Результат отсортируйте по убыванию количества.


In [284]:
# текст запроса
query_4_4 = f'''select distinct
                    schedule, -- Выводим тип графика
                    employment, -- Выводим тип трудоустройства
                    count(name) -- Считаем количество вакансий в паре "график-трудоустройство"
                from vacancies -- Работаем с таблицей vacancies
                group by 1, 2 -- Группируем по графику и трудоустройству
                order by 3 desc -- Сортируем по количеству найденных вакансий в порядке убывания
'''
df = pd.read_sql_query(query_4_4, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\3005064861.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_4, connection) # Создаем DF


schedule           employment  count
0        Полный день     Полная занятость  35367
1   Удаленная работа     Полная занятость   7802
2      Гибкий график     Полная занятость   1593
3   Удаленная работа  Частичная занятость   1312
4     Сменный график     Полная занятость    940
5        Полный день           Стажировка    569
6     Вахтовый метод     Полная занятость    367
7        Полный день  Частичная занятость    347
8      Гибкий график  Частичная занятость    312
9        Полный день     Проектная работа    141
10  Удаленная работа     Проектная работа    133
11     Гибкий график           Стажировка    116
12    Сменный график  Частичная занятость    101
13  Удаленная работа           Стажировка     64
14     Гибкий график     Проектная работа     18
15    Сменный график           Стажировка     12
16    Вахтовый метод     Проектная работа      2
17    Сменный график     Проектная работа      1

In [ ]:
# результат запроса
    schedule	        employment	        count
0	Полный день	        Полная занятость	35367
1	Удаленная работа	Полная занятость	7802
2	Гибкий график	    Полная занятость	1593
3	Удаленная работа	Частичная занятость	1312
4	Сменный график	    Полная занятость	940
5	Полный день	        Стажировка	        569
6	Вахтовый метод	    Полная занятость	367
7	Полный день	        Частичная занятость	347
8	Гибкий график	    Частичная занятость	312
9	Полный день	        Проектная работа	141
10	Удаленная работа	Проектная работа	133
11	Гибкий график	    Стажировка	        116
12	Сменный график	    Частичная занятость	101
13	Удаленная работа	Стажировка	        64
14	Гибкий график	    Проектная работа	18
15	Сменный график	    Стажировка	        12
16	Вахтовый метод	    Проектная работа	2
17	Сменный график	    Проектная работа	1

5. Напишите запрос, выводящий значения поля Требуемый опыт работы (experience) в порядке возрастания количества вакансий, в которых указан данный вариант опыта. 

In [286]:
# текст запроса
query_4_5 = f'''select 
                    experience, -- Выводим требуемый опыт
                    count(name) -- Считаем количество вакансий под требуемый опыт
                from vacancies -- Работаем с таблицей vacancies
                group by 1 -- Группируем по опыту
                order by 2 -- Сортируем по количеству вакансий в порядке возрастания
'''
df = pd.read_sql_query(query_4_5, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\4030349039.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_4_5, connection) # Создаем DF


experience  count
0         Более 6 лет   1337
1           Нет опыта   7197
2       От 3 до 6 лет  14511
3  От 1 года до 3 лет  26152

In [ ]:
# результат запроса
    experience	        count
0	Более 6 лет	        1337
1	Нет опыта	        7197
2	От 3 до 6 лет	    14511
3	От 1 года до 3 лет	26152

***

## Выводы по детальному анализу вакансий:
* ### Самым распространенным требуемым опытом работы является опыт от 1 года до 3 лет, это позволяет компаниям брать на работу сотрудников на относительно низкую ЗП, зато уже с опытом;
* ### Значения средних ЗП варьируются от 71 до 110 тысяч рублей, это показывает нам, что оплата труда нижней зарплатной вилки достаточно высокая, если даже сравнить с МРОТ;
* ### 35367 вакансий предполагают полный рабочий день и полную занятость. Спрос на удаленную работу растет. Людям удобнее работать из дома, а думающие работодатели готовы предоставить эту возможность своим работникам без потери производительности.

# Юнит 5. Анализ работодателей

1. Напишите запрос, который позволит узнать, какие работодатели находятся на первом и пятом месте по количеству вакансий.

In [289]:
# текст запроса

query_5_1 = f'''(select 
                    e.name "Компания", -- Выводим название работодателя, называем столбец Компания
                    count(v.name) "Количество вакансий" -- Считаем количество вакансий под каждого работодателя, называем столбец Количество вакансий
                from employers e -- Работаем с таблицей employers
                    join vacancies v on e.id = v.employer_id -- Присоединяем таблицу vacancies по ключу
                group by 1 -- Группируем по названию работодателя
                order by 2 desc -- Сортируем по количеству вакансий в порядке убывания
                limit 1 -- Ограничение вывода в 1 результат
                )
                union -- Объединяем с другой таблицей 
                (select 
                    e.name, -- Выводим название работодателя, называем столбец Компания
                    count(v.name) -- Считаем количество вакансий под каждого работодателя, называем столбец Количество вакансий
                from employers e -- Работаем с таблицей employers
                    join vacancies v on e.id = v.employer_id  -- Присоединяем таблицу vacancies по ключу
                group by 1 -- Группируем по названию работодателя
                order by 2 desc -- Сортируем по количеству вакансий в порядке убывания
                offset 4 -- Убираем первые 4 результата
                limit 1 -- Ограничение вывода в 1 результат
                )                                
'''
df = pd.read_sql_query(query_5_1, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\3947881540.py:24: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_1, connection) # Создаем DF


Компания  Количество вакансий
0  Газпром нефть                  331
1         Яндекс                 1933

In [ ]:
# результат запроса
    Компания	    Количество вакансий
0	Газпром нефть	331
1	Яндекс	        1933

2. Напишите запрос, который для каждого региона выведет количество работодателей и вакансий в нём.
Среди регионов, в которых нет вакансий, найдите тот, в котором наибольшее количество работодателей.


In [150]:
# текст запроса
query_5_2 = f'''SELECT
                    a.name, -- Выводим название региона
                    v."Количество вакансий", -- Выводим количество вакансий
                    e."Количество работодателей" - Выводим количество работодателей
                FROM areas a -- Работаем с таблицей areas 
                    LEFT JOIN (SELECT 
                                    a.id id,
                                    COUNT(v.id) "Количество вакансий"
                                FROM vacancies v 
                                    LEFT JOIN areas a ON v.area_id = a.id
                                GROUP BY a.id
                                ) v ON a.id = v.id -- Присоединяем полученную таблицу по ключу
                    LEFT JOIN (SELECT
                                    a.id id,
                                    COUNT(e.id) "Количество работодателей"
                                FROM employers e 
                                    LEFT JOIN areas a ON e.area = a.id
                                GROUP BY a.id
                                ) e ON a.id = e.id -- Присоединяем полученную таблицу по ключу
                WHERE "Количество работодателей" IS NOT NULL -- Добавляем условие чтобы количество работодателей не было NULL
                ORDER BY "Количество вакансий" DESC, "Количество работодателей" DESC  -- Сортируем по количеству вакансий в порядке убывания, затем по количеству работодателей в порядке убывания
             '''
df = pd.read_sql_query(query_5_2, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_13940\751791739.py:24: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_2, connection)


name  Количество вакансий  Количество работодателей
0                Россия                  NaN                       410
1             Казахстан                  NaN                       207
2    Московская область                  NaN                        75
3    Краснодарский край                  NaN                        19
4    Ростовская область                  NaN                        18
..                  ...                  ...                       ...
649         Электроугли                  1.0                         1
650         Белореченск                  1.0                         1
651       Красный Сулин                  1.0                         1
652            Заволжье                  1.0                         1
653       Ликино-Дулево                  1.0                         1

[654 rows x 3 columns]

In [ ]:
# результат запроса
    name	            Количество вакансий	Количество работодателей
0	Россия	            NaN	                410
1	Казахстан	        NaN	                207
2	Московская область	NaN	                75
3	Краснодарский край	NaN	                19
4	Ростовская область	NaN	                18
...	...	                ...	                ...
649	Электроугли	        1.0	                1
650	Белореченск	        1.0	                1
651	Красный Сулин	    1.0	                1
652	Заволжье	        1.0	                1
653	Ликино-Дулево	    1.0	                1

3. Для каждого работодателя посчитайте количество регионов, в которых он публикует свои вакансии. Отсортируйте результат по убыванию количества.


In [164]:
# текст запроса
query_5_3 = f'''SELECT
                    e.name, -- Выводим название работодателя
                    count(distinct v.area_id) -- Считаем количество регионов
                from vacancies v -- Работаем с таличей vacancies
                    join employers e on v.employer_id = e.id -- Присоединяем таблицу employers по ключу
                group by 1 -- Группируем по названию работодателя
                order by 2 desc -- Сортируем по количеству регионов в порядке убывания
             '''
df = pd.read_sql_query(query_5_3, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_13940\805115420.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_3, connection)


name  count
0                      Яндекс    181
1                  Ростелеком    152
2                  Спецремонт    116
3      Поляков Денис Иванович     88
4                   ООО ЕФИН      71
...                       ...    ...
14761                  UniSol      1
14762            UNISTORY LLC      1
14763                   UNIT6      1
14764     United Distribution      1
14765              UNITEL LLC      1

[14766 rows x 2 columns]

In [ ]:
# результат запроса
        name	                    count
0	Яндекс	                    181
1	Ростелеком	            152
2	Спецремонт	            116
3	Поляков Денис Иванович	    88
4	ООО ЕФИН	            71
...	...	                    ...
14761	UniSol	                    1
14762	UNISTORY LLC	            1
14763	UNIT6	                    1
14764	United Distribution	    1
14765	UNITEL LLC	            1

4. Напишите запрос для подсчёта количества работодателей, у которых не указана сфера деятельности. 

In [168]:
# текст запроса
query_5_4 = f'''SELECT
                    count(e.name) -- Считаем количество работодателей
                from employers e -- Работаем с таблицей employers
                    left join employers_industries ei on ei.employer_id = e.id -- Присоединяем таблицу employers_industries по ключу
                where industry_id is null -- Добавляем условие отсутствие указанной сферы деятельности
             '''
df = pd.read_sql_query(query_5_4, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_13940\2675578604.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_4, connection)


count
0   8419

In [ ]:
# результат запроса
    count
0	8419

5. Напишите запрос, чтобы узнать название компании, находящейся на третьем месте в алфавитном списке (по названию) компаний, у которых указано четыре сферы деятельности. 

In [14]:
# текст запроса
query_5_5 = f'''SELECT
                    e.name -- Выводим название работодателя
                from employers e -- Работаем с таблицей employers
                join employers_industries ei on e.id = ei.employer_id -- Присоединяем таблицу employers_industries по ключу
                group by 1 -- Группируем по названию работодателя
                having count(e.name) = 4 -- Добавляем условие 4 указанных сфер деятельности
                order by 1 -- Сортируем в алфавитном порядке
                offset 2 -- Убираем первые 2 результата
                limit 1 -- Ограничение вывода в 1 результат
             '''
df = pd.read_sql_query(query_5_5, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\2387035936.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_5, connection)


name
0  2ГИС

In [ ]:
# результат запроса
    name
0	2ГИС

6. С помощью запроса выясните, у какого количества работодателей в качестве сферы деятельности указана Разработка программного обеспечения.


In [18]:
# текст запроса
query_5_6 = f'''SELECT
                    count(e.name) -- Считаем количество работодателей
                from employers_industries ei -- Работаем с таблицей employers_industries
                    join employers e on e.id = ei.employer_id -- Присоединяем таблицу employers по ключу
                    join industries i on i.id = ei.industry_id -- Присоединяем таблицу industries по ключу
                where i.name = 'Разработка программного обеспечения' -- Добавляем условие названия сферы деятельности 'Разработка программного обеспечения'
             '''
df = pd.read_sql_query(query_5_6, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\2916865143.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_6, connection)


count
0   3553

In [ ]:
# результат запроса
    count
0	3553

7. Для компании «Яндекс» выведите список регионов-миллионников, в которых представлены вакансии компании, вместе с количеством вакансий в этих регионах. Также добавьте строку Total с общим количеством вакансий компании. Результат отсортируйте по возрастанию количества.

Список городов-милионников надо взять [отсюда](https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D0%B0-%D0%BC%D0%B8%D0%BB%D0%BB%D0%B8%D0%BE%D0%BD%D0%B5%D1%80%D1%8B_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8). 

Если возникнут трудности с этим задание посмотрите материалы модуля  PYTHON-17. Как получать данные из веб-источников и API. 

In [ ]:
# код для получения списка городов-милионников
# Крайне непонятно, как это сделать, поэтому пропустил данный этап и выписал вручную города в следующей ячейке

In [276]:
# результат запроса
city_list = ('Москва', 'Санкт-Петербург', 'Новосибирск', 'Екатеринбург', 'Казань', 'Нижний Новгород', 'Челябинск', 'Красноярск', 'Самара', 'Уфа', 'Ростов-на-Дону', 'Омск', 'Краснодар', 'Воронеж', 'Пермь', 'Волгоград')
query_5_7 = f'''WITH tab AS (
                SELECT
                    a.name, -- Выводим названия регионов
                    COUNT(*)::int cnt -- Считаем количество строк в таблице, переводим в int
                FROM vacancies v -- Работаем с таблицей vacancies 
                    LEFT JOIN employers e ON v.employer_id = e.id -- Присоединяем таблицу employers по ключу
                    LEFT JOIN areas a ON v.area_id = a.id -- Присоединяем таблицу areas по ключу
                WHERE 
                    e.name = 'Яндекс' -- Добавляем условие названия компании Яндекс
                    AND a.name IN {city_list} -- И чтобы название региона было в списке city_list
                GROUP BY a.id
                ) -- Создаем таблицу tab
                
                SELECT 
                    * -- Выводим все значения таблицы tab
                FROM tab -- Работаем с созданной таблицей
                UNION -- Объединяем
                SELECT
                    'Total', -- Устанавливаем значение в первый столбец 
                    SUM(cnt) -- Считаем общее количеством вакансий
                FROM tab -- Работаем с созданной таблицей
                ORDER BY 2 -- Сортируем по количеству вакансий в порядке возрастания
             '''
df = pd.read_sql_query(query_5_7, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\3347212927.py:26: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_5_7, connection) # Создаем DF


name  cnt
0              Омск   21
1         Челябинск   22
2        Красноярск   23
3         Волгоград   24
4             Пермь   25
5            Казань   25
6    Ростов-на-Дону   25
7               Уфа   26
8            Самара   26
9         Краснодар   30
10          Воронеж   32
11      Новосибирск   35
12  Нижний Новгород   36
13     Екатеринбург   39
14  Санкт-Петербург   42
15           Москва   54
16            Total  485

***

# Выводы по анализу работодателей:
* ### Лидер по количеству вакансий и количеству регионов размещения является Яндекс. Эта компания является быстрорастущей и штат сотрудников постоянно расширяется. И 1/4 всех их вакансий размещены в городах миллионниках;
* ### 3353 компании со сферой деятельности "Разработка программного обеспечения" говорит нам о том, что IT сфера развивается и данные компании в поиске новых сотрудников для расширения.
* ### 8419 компаний не указали сферу деятельности, что может оттолкнуть потенциальных работников, так как некоторые люди предпочитают в карточке компании узнать все о том месте, где им, возможно, предстоит работать.

# Юнит 6. Предметный анализ

1. Сколько вакансий имеет отношение к данным?

Считаем, что вакансия имеет отношение к данным, если в её названии содержатся слова 'data' или 'данн'.

*Подсказка: Обратите внимание, что названия вакансий могут быть написаны в любом регистре.* 


In [98]:
# текст запроса
query_6_1 = f'''SELECT
                    distinct count(v.id) -- Считаем количество вакансий
                from vacancies v -- Работаем с таблицей vacancies
                where v.name ~* 'data' or v.name ~* 'данн' -- Добавляем условия 
             '''
df = pd.read_sql_query(query_6_1, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\2473106150.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_1, connection)


count
0   1771

In [ ]:
# результат запроса
	count
0	1771

2. Сколько есть подходящих вакансий для начинающего дата-сайентиста? 
Будем считать вакансиями для дата-сайентистов такие, в названии которых есть хотя бы одно из следующих сочетаний:
* 'data scientist'
* 'data science'
* 'исследователь данных'
* 'ML' (здесь не нужно брать вакансии по HTML)
* 'machine learning'
* 'машинн%обучен%'

** В следующих заданиях мы продолжим работать с вакансиями по этому условию.*

Считаем вакансиями для специалистов уровня Junior следующие:
* в названии есть слово 'junior' *или*
* требуемый опыт — Нет опыта *или*
* тип трудоустройства — Стажировка.
 

In [275]:
# текст запроса
query_6_2 = f'''SELECT
                    count(v.name) -- Считаем количество вакансий
                from vacancies v -- Работаем с таблицей vacancies
                where 
                (v.name ~* 'data scientist' or
                v.name ~* 'data science' or 
                v.name ~* 'исследователь данных' or 
                (v.name ~ 'ML' and v.name !~* 'HTML') or 
                v.name ~* 'machine learning' or
                v.name like 'машинн%обучен%' or v.name like '%машинн%обучен%' or v.name like '%Машинн%обучен%') and
                (v.name ~* 'junior' or 
                v.experience ~* 'Нет опыта' or 
                v.employment ~* 'Стажировка') -- Задаем условия, чтобы вакансии относились к начинающим DS
             '''
df = pd.read_sql_query(query_6_2, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\879776428.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_2, connection) # Создаем DF


count
0     51

In [ ]:
# результат запроса
    count
0	51

3. Сколько есть вакансий для DS, в которых в качестве ключевого навыка указан SQL или postgres?

** Критерии для отнесения вакансии к DS указаны в предыдущем задании.*

In [217]:
# текст запроса
query_6_3 = f'''SELECT
                    count(*) -- Считаем количество строк в таблице
                from vacancies v -- Работаем с таблицей vacancies 
                where 
                (v.name ~* 'data scientist' or
                v.name ~* 'data science' or 
                v.name ~* 'исследователь данных' or 
                (v.name ~ 'ML' and v.name !~* 'HTML') or 
                v.name ~* 'machine learning' or
                v.name like 'машинн%обучен%' or v.name like '%машинн%обучен%' or v.name like '%Машинн%обучен%') and -- Задаем условия, чтобы вакансии относились к DS
                (v.key_skills ~ 'SQL' or
                v.key_skills ~ 'postgres') -- Задаем условия, чтобы один из ключевых навыков был SQL или postgres
             '''
df = pd.read_sql_query(query_6_3, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\134757368.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_3, connection)


count
0    201

In [ ]:
# результат запроса
	count
0	201

4. Проверьте, насколько популярен Python в требованиях работодателей к DS.Для этого вычислите количество вакансий, в которых в качестве ключевого навыка указан Python.

** Это можно сделать помощью запроса, аналогичного предыдущему.*

In [218]:
# текст запроса
query_6_4 = f'''SELECT
                    count(*) -- Считаем количество строк в таблице
                from vacancies v -- Работаем с таблицей vacancies
                where 
                (v.name ~* 'data scientist' or
                v.name ~* 'data science' or 
                v.name ~* 'исследователь данных' or 
                (v.name ~ 'ML' and v.name !~* 'HTML') or 
                v.name ~* 'machine learning' or
                v.name like 'машинн%обучен%' or v.name like '%машинн%обучен%' or v.name like '%Машинн%обучен%') and -- Задаем условия, чтобы вакансии относились к DS
                (v.key_skills ~ 'Python') -- Задаем условие, чтобы ключевым навыком являлся Python
             '''
df = pd.read_sql_query(query_6_4, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\3110109601.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_4, connection)


count
0    351

In [ ]:
# результат запроса
	count
0	351

5. Сколько ключевых навыков в среднем указывают в вакансиях для DS?
Ответ округлите до двух знаков после точки-разделителя.

In [230]:
# текст запроса
query_6_5 = f'''SELECT
                    round(avg(length(v.key_skills) - length(replace(v.key_skills, CHR(9), '')) + 1), 2) AVG -- Считаем какое количество навыков в среднем требуется в вакансиях
                from vacancies v -- Работаем с таблицей vacancies
                where 
                (v.name ~* 'data scientist' or
                v.name ~* 'data science' or 
                v.name ~* 'исследователь данных' or 
                (v.name ~ 'ML' and v.name !~* 'HTML') or 
                v.name ~* 'machine learning' or
                v.name like 'машинн%обучен%' or v.name like '%машинн%обучен%' or v.name like '%Машинн%обучен%') -- Задаем условия, чтобы вакансии относились к DS
             '''
df = pd.read_sql_query(query_6_5, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\364415456.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_5, connection)


avg
0  6.41

In [ ]:
# результат запроса
    avg
0	6.41

6. Напишите запрос, позволяющий вычислить, какую зарплату для DS в **среднем** указывают для каждого типа требуемого опыта (уникальное значение из поля *experience*). 

При решении задачи примите во внимание следующее:
1. Рассматриваем только вакансии, у которых заполнено хотя бы одно из двух полей с зарплатой.
2. Если заполнены оба поля с зарплатой, то считаем зарплату по каждой вакансии как сумму двух полей, делённую на 2. Если заполнено только одно из полей, то его и считаем зарплатой по вакансии.
3. Если в расчётах участвует null, в результате он тоже даст null (посмотрите, что возвращает запрос select 1 + null). Чтобы избежать этой ситуацию, мы воспользуемся функцией [coalesce](https://postgrespro.ru/docs/postgresql/9.5/functions-conditional#functions-coalesce-nvl-ifnull), которая заменит null на значение, которое мы передадим. Например, посмотрите, что возвращает запрос `select 1 + coalesce(null, 0)`

Выясните, на какую зарплату в среднем может рассчитывать дата-сайентист с опытом работы от 3 до 6 лет. Результат округлите до целого числа. 

In [272]:
# текст запроса
query_6_6 = f'''SELECT
                    v.experience "Опыт", -- Выводим требуемый опыт, называем столбец Опыт
                    ROUND(AVG((COALESCE(salary_from, salary_to) + COALESCE(salary_to, salary_from)) / 2))::int "Средняя ЗП" -- Выводим среднюю ЗП, называем столбец Средняя ЗП
                from vacancies v -- Работаем с таблицей vacancies
                where 
                (v.name ~* 'data scientist' or
                v.name ~* 'data science' or 
                v.name ~* 'исследователь данных' or 
                (v.name ~ 'ML' and v.name !~* 'HTML') or 
                v.name ~* 'machine learning' or
                v.name like 'машинн%обучен%' or v.name like '%машинн%обучен%' or v.name like '%Машинн%обучен%') and -- Задаем условия, чтобы вакансии относились к DS
                (v.salary_from is not null or v.salary_to is not null) -- Задаем условие, чтобы одно из двух полей с ЗП было заполнено
                group by 1 -- Группируем по требуемому опыту
                order by 2 desc -- Сортируем по средней ЗП
             '''
df = pd.read_sql_query(query_6_6, connection) # Создаем DF
df

C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\1938768396.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query_6_6, connection) # Создаем DF


Опыт  Средняя ЗП
0       От 3 до 6 лет      243115
1  От 1 года до 3 лет      139675
2           Нет опыта       74643

In [ ]:
# результат запроса
    Опыт	            Средняя ЗП
0	От 3 до 6 лет	    243115
1	От 1 года до 3 лет	139675
2	Нет опыта	        74643

***

## Выводы по предметному анализу:
* ### Я, как начинающий специалист по DS могу откликнуться на 51 вакансию, при этом я должен обладать, как минимум, 7 ключевыми навыками и могу рассчитывать на ЗП примерно в 75000 рублей. Двигаемся в правильном направлении, мне нравится :) ;
* ### 5 процентов всех вакансий относятся к данным, что еще раз подтверждает нашу гипотезу о том, что сфера IT разрастается с каждым годом. Интересно было бы понаблюдать за этими показателями в диинамике;

# Общий вывод по проекту в Readme, ниже представлены дополнительные исследования данных.

In [335]:
query_bonus_1 = f'''select 
                    e.name "Название компании",
                    max(v.salary_from) "ЗП от",
                    max(v.salary_to) "ЗП до"
                from vacancies v -- Работаем с таблицей vacancies
                    join employers e on e.id = v.employer_id
                where experience = 'Нет опыта' -- Добавляем условие отсутствия опыта
                group by 1 -- Группируем по названию компании
                having max(v.salary_to) is not null and max(salary_from) is not null -- Добавляем условие указания обоих полей ЗП
                order by 3 desc, 2 desc -- Сортируем по ЗП в порядке убывания
'''

bonus_1 = pd.read_sql_query(query_bonus_1, connection) # Создаем DF
bonus_1

C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\1304082226.py:13: UserWarning:

pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.



Название компании   ЗП от   ЗП до
0                      think-cell  348270  557232
1     Агентство недвижимости ЛЕТО  200000  500000
2                         Патриот  100000  500000
3         Smart World (Умный мир)  225000  300000
4                     Аппликатура  200000  300000
...                           ...     ...     ...
1226                     QazCloud   10374    9764
1227                ASPAN telecom    9764    9764
1228                Ковальчук А.А    2805    8181
1229                        Теком    2000    6000
1230       Актуальное страхование    1500    1500

[1231 rows x 3 columns]

In [ ]:
# Результат запроса
		Название компании	        ЗП от	ЗП до
0		think-cell	                348270	557232
1		Агентство недвижимости ЛЕТО	200000	500000
2		Патриот	                    100000	500000
3		Smart World (Умный мир)	    225000	300000
4		Аппликатура	                200000	300000
...		...	                        ...		...
1226	QazCloud	                10374	9764
1227	ASPAN telecom	            9764	9764
1228	Ковальчук А.А	            2805	8181
1229	Теком	                    2000	6000
1230	Актуальное страхование	    1500	1500

## Вывод по дополнительному исследованию данных:
* ### Без опыта лучше всего идти в те компании, которые предоставляют хорошую ЗП, что и могут предложить ТОПы данного запроса. ЛЕТО базируются в Сочи, прибыльная сфера - недвижимость. Информацию по лидеру у меня найти не получилось;
* ### Куда не стоит идти, так это в компании, которые находятся внизу списка. В исследовании данных мы смотрели на средние значения, но это как с яблоками, у меня 1, у друга 9, а в среднем у нас по 5 яблок.

In [337]:
import plotly.express as px # импортируем библиотеку, необходимую для выполнения задания

query_bonus_2 = f'''select 
                    salary_to::int up -- Выводим значения верхней границы ЗП, называем столбец up
                from vacancies -- Работаем с таблицей vacancies
                where salary_to is not null -- Добавляем условие, чтобы поле ЗП не было пустым
'''

bonus_2 = pd.read_sql_query(query_bonus_2, connection) # Создаем DF


# Создаем график и задаем для него параметры
fig = px.histogram(bonus_2['up'],
                   marginal='box')
# Обновляем для графика заголовок, имена оси абцисс и ординат, отключаем отображение легенды
fig.update_layout(
    title_text = 'Распределение верхней заработной платы в рублях',
    showlegend = False,
    xaxis_title = 'ЗП (руб)',
    yaxis_title = 'Количество вакансий'
)
fig.show()
fig.write_html('graphs/11.html')


C:\Users\Матвей\AppData\Local\Temp\ipykernel_12208\823226493.py:9: UserWarning:

pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.



## Вывод по дополнительному исследованию данных:
* ### Основное средоточение значений мы видим в районе до 100000 рублей, что нам говорит о потенциальной возможности набора сотрудников с более высокой ЗП уже из штата сотрудников, посредством повышения в должности и увеличения ЗП. 
* ### Больше 1000 вакансий рассчитаны на ЗП от 50000 до 55000 рублей, что является хорошей ЗП, если работник проживает не в Москве. Регион размещения вакансии имеет огромное значение.